//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trizbd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kadriEntities : DbContext
    {
        public kadriEntities()
            : base("name=kadriEntities")
        {
        }
     
        private static kadriEntities _context;

        public static kadriEntities getContext()
        {
            if (_context == null)
                _context = new kadriEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Employment_Contracts> Employment_Contracts { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Salaries> Salaries { get; set; }
        public virtual DbSet<Vacations> Vacations { get; set; }
    }
}
