//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trizbd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaries
    {
        public int Salary_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public string Payment_Type { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
